name: Check Commit

on:
  push:
    branches:
      - '*'

jobs:
  check-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Run checks
        run: |
          npm ci
          npm run lint
          npm run typecheck
          npm test
